### ISSUE TITLE
Wrong Base URL

### ISSUE THREAD

**Issue by antoine1003** [tightenco/ziggy#110]
Hi,
When I try to use `var url_sub = route('user.handleFriends');` it returns  `http://localhost/user/handleFriends` while it should return `http://localhost/site-etudiants/public/user/handleFriends`.
In my **app.config** I have `env('APP_URL', 'http://localhost/site-etudiants/public')`.
I am using Laravel 5.4

**Comment by jcmosaiclearning** [comment]
I'm also seeing this. The Ziggy object definitely has the correct `baseUrl` set per my APP_URL, but it looks like it's never consulted by the `UrlBuilder` object when building out the template that is later used by the Router's `parse` method.

**Comment by antoine1003** [comment]
@jcmosaiclearning Actually, I found an alternative : in your page just put this kind of script
```
<script type="text/javascript">
            var APP_URL =" {!! url('/') !!}"; // I am using laravel so this returns me the base url.
</script>
```
Then in your ziggy stuff just use `APP_URL + 'user/inbox'`
Hope it helps 😉

**Comment by jcmosaiclearning** [comment]
Unfortunately, it doesn't help. The `route` helper function returns the fully formed URL so I'd just be prefixing that with the APP_URL.

I've got a ton of ajax calls that I'd love to have use the `route` helper use in order to find their routes. Then when my backend changes, as long as the route names remain the same, the JS continues to work. I also love the idea of only exposing routes based on predefined groups. Ziggy so far seems to be better than Laroute in this respect, except for this one minor thing.

Unfortunately I've had to do this for now inside of UrlBuilder's setDomain:

```
        if (Ziggy.baseUrl) {
            return Ziggy.baseUrl;
        }
```

**Comment by okmkey45** [comment]
Same issue here. `route('appointment.data')` should return `http://localhost:8080/app/public/appointment/data` but it returns `http://localhost:8080/appointment/data`

Any advices?

**Comment by DanielCoulbourne** [comment]
Hmm. I'll take a look at this today.

**Comment by jcmosaiclearning** [comment]
Awesome! I really like how easy it is to set up routes to expose based on groups with Ziggy as opposed to Laroute, so I'm glad to be able to continue using it. As someone else stated in the other thread(#108), I've downgraded to 0.4 for now which fixes the issue.
