### ISSUE TITLE
How to use static routes with mix and Vuejs

### ISSUE THREAD

**Issue by cviebrock** [tightenco/ziggy#154]
Just starting to use this, and I'm a bit confused about how to use the [artisan command](https://github.com/tightenco/ziggy#artisan-command) in my Vuejs project.

I run the command to generate `resources/assets/js/ziggy.js`, but then what?  I've tried adding `require('./ziggy');` to `app.js`, but do I still need the blade directive?  I think I do in order for the `route()` helper function to exist in JS, but then I think all the routing info is duplicated (i.e. the blade directive and `ziggy.js` define all the route).

And does the artisan command support groups in my `config/ziggy.php`?

Thanks in advance!

**Comment by DanielCoulbourne** [comment]
The command should support your config file.

You'll need to import the route command in your Vue components
`https://github.com/tightenco/ziggy/blob/master/src/js/route.js`

`import route from '/path/to/vendor/tightenco/ziggy/src/js/route.js`
or
`const route = require('/path/to/vendor/tightenco/ziggy/src/js/route.js')`

Hope that makes sense?

**Comment by codytooker** [comment]
Sorry to open a closed topic but I have a similar problem here.  I don't want to use the @route directive so I am using the artisan command and importing the route.js file manually.

I have this in my app.js file

`
import { Ziggy } from './ziggy';
import route from '../../../vendor/tightenco/ziggy/src/js/route';

Vue.mixin({
    methods: {
        route: route
    }
});
`

This seems like this should work however I get the error. 

[Vue warn]: Error in render: "ReferenceError: Ziggy is not defined"

**Comment by codytooker** [comment]
`./ziggy`?

is the file produced from the artisan command

```
	var Ziggy = {
		namedRoutes: {"routes all listed here,  removed for space"}
		baseUrl: 'http://localhost/',
        baseProtocol: 'http',
        baseDomain: 'localhost',
        basePort: false,
        defaultParameters: []
    };

    export {
        Ziggy
    }
```

I was under the impression I could simply import Ziggy and it should work.

**Comment by rodrigopedra** [comment]
Hi @codytooker , I was trying the same setup and looking into `route.js` source it seems that Ziggy should be available globally. The following works:

````js
import Vue from 'vue';
import {Ziggy} from './ziggy';
import route from '../../../vendor/tightenco/ziggy/src/js/route';

window.Ziggy = Ziggy; // this was missing from your setup

Vue.mixin({
    methods: {
        route: route
    }
});
````
 This is the line that looks for the `Ziggy` object in the global scope:

https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L9

**Comment by codytooker** [comment]
@rodrigopedra thanks for the info.  This should work for me.  I'll test it out when I get back to working on the project again.

I think some info like this should probably be added to the readme file around generating the Custom Ziggy file.

**Comment by Onind** [comment]
with the solution from @rodrigopedra i still get this error:

[Vue warn]: Error in mounted hook: "ReferenceError: route is not defined"

**Comment by lgalaz** [comment]
@Onind  did you find a solution? Im getting the same error.

@DanielCoulbourne thanks for this package, its extremely useful. I think that instructions to use it with the artisan command should be included in the readme. Or do you suggest some other way to use it in a way that route info is not set in every view (as when using the blade directive).  
I am trying with the suggestion from @rodrigopedra and getting `"ReferenceError: route is not defined"`
```
import {Ziggy} from './ziggy';
import route from '../../../vendor/tightenco/ziggy/src/js/route';

window.Vue.mixin({
    methods: {
        route: ( name, params, absolute ) => route(name, params, absolute, Ziggy)
    }
});
```

**Comment by agm1984** [comment]
Ok, I think I figured it out. First, dumping all the named routes into a publically-available `<script>` tag and `window.Ziggy` is a leaky abstraction in my opinion.

The solution described in this thread is probably what you want to do with Laravel/Vue.

Here is what I am doing now:
1) Run `php artisan ziggy:generate "resources/js/ziggy.js"` (this will generate the route list into the same folder as your `app.js` file, and this is what makes `import { Ziggy } from './ziggy'` work, assuming you import that into your app.js file.

2) Continuing from step 1, add this to your `app.js` file:
``` javascript
import { Ziggy } from './ziggy';
import route from '../../vendor/tightenco/ziggy/src/js/route';
```

Your relative folder may vary. If you are using VS Code, I recommend the extension `Path Autocomplete` because it will give you typeahead suggestions while typing the path. I usually do something like `import route from '../';` and then follow the dropdown suggestions. It makes it easy to see what folder you are in. Here is a screenshot:
![image](https://user-images.githubusercontent.com/17655219/58124554-5d8ef580-7bc3-11e9-965b-7cdba1650971.png)

3) Create a global mixin right below there in `app.js`:
``` javascript
Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    },
});
```

4) Now you can access `this.route('some.name')` from any Vue component.

5) You will notice that you need to run `php artisan ziggy:generate` every time you change `web.php`. This is horrifically annoying. I tried in my own app to make `laravel-mix` run that command every time a file changed, but it ended up being very non-trivial.

The closest I got was to install `webpack-shell-plugin` and make it so it rebuilt the `ziggy.js` file, but because I am using Webpack V3 (for dynamic imports and bundle splitting, V4 is too buggy), I was encountering some infinite loops where Webpack was rebuilding every time it rebuilt, due to a change in `public/css/app.css` which is post-processed by SASS and Tailwind (in my case).

Your milage will vary. Try it using `onBuildEnd` with `webpack-shell-plugin`. If you are using Webpack V4, you can probably use `afterEmit` (see: https://stackoverflow.com/questions/30312715/run-command-after-webpack-build).

As a stop-gap fix, I have done the following:
layout.blade.php
``` javascript
@if (\App::environment() != 'production')
    @routes
@endif
```

app.js
``` javascript
import route from '../../vendor/tightenco/ziggy/src/js/route';
// ...

if (process.env.NODE_ENV === 'production') {
    const { Ziggy } = require('./ziggy'); // eslint-disable-line global-require
    Vue.mixin({
        methods: {
            route: (name, params, absolute) => route(name, params, absolute, Ziggy),
        },
    });
} else {
    Vue.mixin({
        methods: {
            route,
        },
    });
}
```

webpack.config.js
``` javascript
const plugins = [
    // you can ignore this plugin; it's not related to this Ziggy thread
    new PurgecssPlugin({
        // Specify the locations of any files you want to scan for class names.
        paths: glob.sync([
            path.join(__dirname, 'resources/views/**/*.blade.php'),
            path.join(__dirname, 'resources/js/**/*.vue'),
        ]),
        extractors: [
            {
                extractor: TailwindExtractor,

                // Specify the file extensions to include when scanning for
                // class names.
                extensions: ['html', 'js', 'php', 'vue'],
            },
        ],
    }),
];

if (mix.inProduction()) {
    plugins.push(new WebpackShellPlugin({
        onBuildStart: ['php artisan ziggy:generate resources/js/ziggy.js'],
    }));
}

mix.webpackConfig({
    plugins,
});
```

The important thing to note is that I am pushing the shell plugin only in production mode. Webpack did not like when the plugins array contained falsy and/or non-function values because it assumes `fn.call()` and `fn.apply()` can be used on every entry.

**Comment by lgalaz** [comment]
awesome @agm1984 , i'll give it a try as soon as I can.
thanks.

**Comment by M-Abdullahi** [comment]
Thank you @agm1984. Your solution worked for me.

**Comment by DanielCoulbourne** [comment]
The horrific annoyance of generating routes every time they change is the primary driver behind the decision to include routes in a script tag by default, so as not to confuse new users. Your write up was very good for your use case, though, thanks for contributing that solution.
