### ISSUE TITLE
Bug with query parameters.

### ISSUE THREAD

**Issue by pmochine** [tightenco/ziggy#157]
### Expected Behavior

route('events.venues.show', {event: 1, venue: 2, page: 5, count: 0})

// Returns '/events/1/venues/2?page=5&count=0'

### Current Behavior

route('events.venues.show', {event: 1, venue: 2, page: 5, count: 0})
// Returns '/events/1/venues/2?page=5

### Currently installed Laravel version:
`5.6.**`

### Currently installed Ziggy version
`0.6.6`

My problem is that I want to add the 0 but I cannot.

**Comment by DanielCoulbourne** [comment]
Good call. I'll take a look

**Comment by reinink** [comment]
This is related to this change: #147

And this bug is already noted here as well: https://github.com/tightenco/ziggy/issues/141#issuecomment-385416381

To me, I think the solution here is to ONLY remove values that are `null`. Ziggy should leave values that falsy, like `0` and `''`. In fact, my app just broke because I was expecting to be able to send an empty string, but it was stripped out.

I agree with removing `null` values though.

**Comment by reinink** [comment]
Probably as simple as changing this:

https://github.com/tightenco/ziggy/blob/962672e507678da3e8324a0dea2ad96411df9852/src/js/route.js#L102

To something like this:

```js
if (this.queryParams[key] !== undefined && this.queryParams[key] !== null) { 
```

**Comment by DanielCoulbourne** [comment]
Sorry I've taken so long getting to this. Been swamped but I'm free all weekend and all week next week. If you drop a PR of @reinink 's solution with a test I'll merge it today, otherwise I'll get around to this in that time.
