### ISSUE TITLE
Replace webpack with Microbundle?

### ISSUE THREAD

**Issue by bradlc** [tightenco/ziggy#184]
Hey 👋

I have a couple of questions regarding the JavaScript for Ziggy:

Would you consider replacing webpack with Rollup, via [Microbundle](https://github.com/developit/microbundle)? I have done this on a branch and the UMD bundle is now 1340 bytes gzipped, down from 2161 bytes (**38% smaller**). Another benefit of this is that there are **6 fewer dependencies**. I’d be happy to submit a pull request if you’re interested.

Also, as far as I can tell Ziggy is not available on npm. Would you ever consider publishing it?

Thanks,
Brad

**Comment by DanielCoulbourne** [comment]
As far as publishing on on NPM, much of the functionality of Ziggy depends on Laravel, and thus needs to be published on Composer. We COULD publish a version of it, but it would  belife  missing a lot of features.

As far as switching to roll up, I want @ankurk91 to weigh in on that as he’s our resident JS build pipeline expert.

**Comment by ankurk91** [comment]
### quick dependency size test
```
cd ~
mkdir microbundle-test
cd microbundle-test
yarn init -y
yarn add microbundle --dev
du -sh node_modules
# 152 MB
```
```
cd ~
git clone https://github.com/tightenco/ziggy.git -b master --single-branch --depth=10
cd ziggy
yarn install
du -sh node_modules
#  63 MB including `mocha`
```
Current solution is half in size. 

microbundle is wrapper around rollup, i want the solution to be close metal.
If you can come up with a pure rollup [solution](https://github.com/rollup/rollup-starter-lib) that would be great. 

**Your solution should satisfy below requirements.**
* UMD build
* `babel-preset-env`; so that we can specify the browsers that Ziggy will support
* IE 11 support via `babel-plugin-transform-object-assign` polyfill
* expose `window.route` so that it works without any module bundler
* generate minified and non-minified files both

Lastly; I could have gone with `rollup` [initially](https://github.com/tightenco/ziggy/pull/87) but didn't because webpack user base is larger than rollup and it is easy to find support and help.

**Comment by DanielCoulbourne** [comment]
What I'm gathering from the comments on #185 and #188 is that we can gain a much smaller minified file if we get rid of IE11 polyfills, but if we choose to keep polyfills we end up with a bundle around the same size.

Is that about right @ankurk91 and @bradlc ?

**Comment by ankurk91** [comment]
There is only IE11 specific [polyfill](https://github.com/tightenco/ziggy/blob/0f59b703236f6b19002bc28d1d3eafcbf479bd43/dist/js/route.js#L154) ; that is for Object.assign. 

Rest of them added by babel for other reasons, for example

https://github.com/tightenco/ziggy/blob/0f59b703236f6b19002bc28d1d3eafcbf479bd43/dist/js/route.js#L107

https://github.com/tightenco/ziggy/blob/0f59b703236f6b19002bc28d1d3eafcbf479bd43/dist/js/route.js#L105

https://github.com/tightenco/ziggy/blob/0f59b703236f6b19002bc28d1d3eafcbf479bd43/dist/js/route.js#L156

**Comment by ankurk91** [comment]
Yes, if we keep go with rollup and Babel, it will ended up with same bundle size.

**Comment by DanielCoulbourne** [comment]
Seems like we should just stick with webpack then, unless there is a very compelling reason to switch.

**Comment by ankurk91** [comment]
Agree, i can serve additional 3kb if it enables my app to support more browsers.

**Comment by bradlc** [comment]
Hey @ankurk91. I really appreciate you taking the time to look into the alternatives, I just haven’t had the time this week to respond to your queries. Sorry about that! I will put a PR together by the end of the weekend. Thanks!

**Comment by DanielCoulbourne** [comment]
@bradlc Any movement on this? I'd love to compare your PR to the two @ankurk91 put together and see what we can do.

**Comment by bradlc** [comment]
@DanielCoulbourne https://github.com/tightenco/ziggy/pull/193
