### ISSUE TITLE
Is it possible use this package with Laravel and twig?

### ISSUE THREAD

**Issue by indapublic** [tightenco/ziggy#270]

**Comment by bakerkretzmar** [comment]
@indapublic yes, it should be possible. If you're using a mix of Blade views and Twig, you could use the `@routes` directive anywhere that you're using regular Blade syntax.

If you're doing all your templating with Twig, depending on your setup, you can create a Twig extension or find another way to call: `app('Tightenco\Ziggy\BladeRouteGenerator')->generate($group)` to generate and output the Javascript for the routes.

Otherwise, generate the Javascript beforehand [using `php artisan ziggy:generate`](https://github.com/tightenco/ziggy#artisan-command) and include it using a script tag.
