### ISSUE TITLE
add config publish option

### ISSUE THREAD

**Issue by ctf0** [tightenco/ziggy#43]
i don't think using `php artisan vendor:publish --provider="..."` is harder and more time consuming than creating the ziggy config file manually.

**Comment by DanielCoulbourne** [comment]
I am less opposed to this than I initially was, but I'm still not totally sold.

I think people see a command in the documentation and they want to run it. Adding a `vendor:publish` to a repo makes it feel like an extra step to getting started, even though it is optional.

I'm also not sold on the idea that running an artisan command is easier than just creating a php file.

Sorry for being a stickler about this I just don't like `vendor:publish` very much personally haha

**Comment by DanielCoulbourne** [comment]
Leaving this open to hear more opinions from the community. I'm fine with being wrong about this.

**Comment by mattstauffer** [comment]
I don't love config files. But, in not liking them, I only publish them when i need them. I'm not sure whether I agree that people will just run it because it's there? I'm torn because i'm not 100% sure that it's better--if you hate it, you hate it, and it's really not that hard for people to make it themselves. So you don't *have* to. No question. But I just want to push back on the part of it that assumes that it being there will mean everyone will publish.

But who knows, I'm just speaking for me, anyway.

**Comment by ankurk91** [comment]
We love command line.
It would be great if artisan can copy a sample config file from `vendor` to project `config` folder.

**Comment by JesseLeite** [comment]
I rarely use it, but always like seeing sample configs in vendor folder.  Apparently Taylor recently made `artisan vendor:publish` less intrusive, as it now asks `Y/N` before publishing each file I think?

**Comment by DanielCoulbourne** [comment]
Okay fine.  😛 
I'll merge a PR with an artisan vendor publish. Probably won't include it in the docs for now. Just there for an example config.

If you PR, please write up a nice little comment for each config option for inline documentation.
