### ISSUE TITLE
Blacklist after white

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [tightenco/ziggy#76]
it would be nice to have blacklist applied after whitelist.
this config
```php
return [
    'whitelist' => ['api::*'],
    'blacklist' => ['api::admin*'],
];
```
suppose to expose all 'api::*' except for 'api::admin*'. but now i get just all whitelisted without exceptions.
or the other idea - to make lists include sub-lists. like
```php
<?php
return [
    'whitelist' => [
        'api::*',
        'blacklist' => ['api::admin*']
    ],
    //    'blacklist' => ['api::admin*'],
];
```
by the way - great package! :)

**Comment by DanielCoulbourne** [comment]
Thanks! 

The issue is that, while it seems intuitive for your situation to have blacklist go after whitelist, there are just as many situations where someone might want to do the opposite.

Ideally we would just work down the list from top to bottom for each route but so far that has seemed kind of daunting to me and I'm afraid it might be a bit slow.

If you're up to a PR I wouldn't mind trying it out.
